---
- name: test
  hosts: all
  gather_facts: false
  vars:
    ansible_user: ubuntu
  become: yes
  tasks:
    - name: Wait for service to be ready
      ansible.builtin.wait_for_connection:
        delay: 20
        timeout: 60

    - name: Install Nginx Web Server on Debian Family
      apt:
        name: nginx
        state: latest
        update_cache: yes