version: '2.3'
services:
  vault:
      hostname: vault
      container_name: vault
      image: hashicorp/vault:1.15
      environment:
        VAULT_ADDR: "http://127.0.0.1:8200"
        VAULT_API_ADDR: "http://127.0.0.1:8200"
      ports:
        - "8200:8200"
      volumes:
        - ./volumes/vault/file:/vault/file:rw
      cap_add:
        - IPC_LOCK
      entrypoint: vault server -dev -dev-listen-address="0.0.0.0:8200" -dev-root-token-id="education"
