---
name: terraform-docs
on:
  push:
    branches:
      - terraform-04
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: terraform-04

    - name: Render terraform docs and push changes back to PR
      uses: terraform-docs/gh-actions@main
      with:
        working-dir: 04/src/vpc/
        output-file: terr-docs.md
        output-method: inject
        git-push: "false"
